### ISSUE TITLE
Add solutions in PHP

### ISSUE THREAD

**Issue by hhhrrrttt222111** [hhhrrrttt222111/CodeChef#108]

**Comment by WazeAzure** [comment]
What is the issue???? which one need to be done?

**Comment by hhhrrrttt222111** [comment]
> What is the issue???? which one need to be done?

Add problem solution in PHP for every question

**Comment by DaviLhlapakRosa** [comment]
I can take this?

**Comment by hhhrrrttt222111** [comment]
> I can take this?

Sure
