### ISSUE TITLE
Adding name of contributers in the Readme.md file

### ISSUE THREAD

**Issue by Ashishjagrawal** [hhhrrrttt222111/CodeChef#182]
It will be great if we add the names and profiles of the people in the Readme.md file who contributed to this repository.

like this:-
![Screenshot (2)](https://user-images.githubusercontent.com/44999678/97321784-3f87f300-1895-11eb-8829-83a6ae5ad1a8.png)

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @Ashishjagrawal for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @sayand0122 for code
@all-contributors please add @Yash0605 for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @sayand0122 for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @Yash0605 for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @DesmondWasHere for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @Yash0605 for code

**Comment by hhhrrrttt222111** [comment]
@all-contributors please add @DesmondWasHere for code
