### ISSUE TITLE
nth smallest element in Binary Search Tree

### ISSUE THREAD

**Issue by mahesh-11102** [hhhrrrttt222111/CodeChef#295]
`Question:` Write a Java program to identify the kth smallest element in the binary search tree ?

`my code Output: `

![image](https://user-images.githubusercontent.com/77436328/135504705-b4c48c35-2be8-4a65-9a69-db264fa26e41.png)

As a part of `Hacktoberfest'21` @hhhrrrttt222111 ,   please assign this issue to me

**Comment by hhhrrrttt222111** [comment]
> `Question:` Write a Java program to identify the kth smallest element in the binary search tree ?
> 
> `my code Output: `
> 
> ![image](https://user-images.githubusercontent.com/77436328/135504705-b4c48c35-2be8-4a65-9a69-db264fa26e41.png)
> 
> As a part of `Hacktoberfest'21` @hhhrrrttt222111 , please assign this issue to me

I will merge with hacktoberfest label when u put a PR
