### ISSUE TITLE
Chef and Laddus For Children 

### ISSUE THREAD

**Issue by syamala27** [hhhrrrttt222111/CodeChef#303]
`Question link :` https://www.codechef.com/problems/CCBTS03/

as a part of `Hacktoberfest'21` @hhhrrrttt222111  please assign this issue to me

**Comment by hhhrrrttt222111** [comment]
> `Question link :` https://www.codechef.com/problems/CCBTS03/
> 
> as a part of `Hacktoberfest'21` @hhhrrrttt222111 please assign this issue to me

You can put a PR. Will merge if it is valid
