### ISSUE TITLE
Want to add Codeforces #744 Problem D

### ISSUE THREAD

**Issue by tom635** [hhhrrrttt222111/CodeChef#402]
Adding codeforces Problems
Assign me this issue 
Problem link:https://codeforces.com/problemset/problem/1579/D

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by hhhrrrttt222111** [comment]
@navjotdadwal @tom635 
Add Codeforces problems here https://github.com/hhhrrrttt222111/CodeChef/tree/main/MORE%20CODING%20PLATFORMS/Codeforces .

Make sure you create a new folder inside with the problem name.

**Comment by rahul-aggarwal000005** [comment]
Adding codeforces Problems
Assign me this issue
Problem link:https://codeforces.com/contest/1581/problem/B

**Comment by Shivamvats2102** [comment]
Adding codeforces Problems
Assign me this issue
Problem link:https://codeforces.com/problemset/problem/1574/D
