### ISSUE TITLE
Update rules in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by bineethkumar** [hhhrrrttt222111/CodeChef#481]
I guess repo of a problem looks good by changing rule to add Question, Explanation, Examples and constraints of a problem in a README file (inside problem folder) itself.🤔

**Comment by hhhrrrttt222111** [comment]
> I guess repo of a problem looks good by changing rule to add Question, Explanation, Examples and constraints of a problem in a README file (inside problem folder) itself.🤔

Feel free to add those while making your contribution
