### ISSUE TITLE
The Project is excluded from hacktoberfest 😢

### ISSUE THREAD

**Issue by MQ-xz** [hhhrrrttt222111/CodeChef#606]
![image](https://user-images.githubusercontent.com/51271771/135757803-25e4fe14-cf01-424d-b1c1-1f1d439c3e45.png)

**Comment by joshiaastha** [comment]
Kindly, all the maintainers look into this please.

**Comment by ipsitagoel** [comment]
@hhhrrrttt222111 please look into this issue!

**Comment by hhhrrrttt222111** [comment]
![h](https://user-images.githubusercontent.com/43471295/135870538-2df95623-367b-4158-90b8-2689b47428fb.PNG)
