### ISSUE TITLE
Exclude Project 

### ISSUE THREAD

**Issue by aritrasen12345** [hhhrrrttt222111/CodeChef#613]
![Screenshot (91)](https://user-images.githubusercontent.com/71816694/135768532-8018f8fa-a9cb-4b1b-a697-1f6eaa2e9ffb.png)

Project Excluded ??!! Why ??

**Comment by realhunter7869** [comment]
Adding `hacktoberfest` as the topic to this project will resolve this issue @hhhrrrttt222111

**Comment by hhhrrrttt222111** [comment]
> ![Screenshot (91)](https://user-images.githubusercontent.com/71816694/135768532-8018f8fa-a9cb-4b1b-a697-1f6eaa2e9ffb.png)
> 
> Project Excluded ??!! Why ??

No idea ;(

**Comment by vishalsinghhh** [comment]
Any chances that this issue can be resolved? @hhhrrrttt222111

**Comment by aritrasen12345** [comment]
> > ![Screenshot (91)](https://user-images.githubusercontent.com/71816694/135768532-8018f8fa-a9cb-4b1b-a697-1f6eaa2e9ffb.png)
> > Project Excluded ??!! Why ??
> 
> No idea ;(

😢😢😢😢😢😢

**Comment by hhhrrrttt222111** [comment]
![h](https://user-images.githubusercontent.com/43471295/135870440-f1bf8aa2-7e58-42a9-887d-9c54df594e5b.PNG)
